/:
  controller: Main
  action: home

/page:
  controller: Page
  action: show

/sinscrire:
  controller: User
  action: register

/sinscrire_post:
  controller: User
  action: registerPost

/login:
  controller: User
  action: login

/login_post:
  controller: User
  action: loginPost

/logout:
  controller: User
  action: logout

/dashboard:
  controller: Backoffice
  action: dashboard
